### ISSUE TITLE
command line arg '-rc' was not understood

### ISSUE THREAD

**Issue by shp4rk** [tandasat/Hypervisor-101-in-Rust#1]
On Debian 12, when I ran `cargo xtask bochs-intel`, the bochs were not executed since it could not parse `-rc` option that is given by:
https://github.com/tandasat/Hypervisor-101-in-Rust/blob/5bdb5e6d99d638984162b9c55078ea1786e6c5e0/xtask/src/bochs.rs#L60
I could work around the error by removing `-rc` option, but I am curious if it's me that's wrong and I should've used another bochs.

**Comment by tandasat** [comment]
Did you build Bochs from the specified fork and branch? It is weird to me that the command line option is not accepted there while it is on Ubuntu. Please post an error message.

You may also remove the flag. In this case, a Bochs debugger will break-in at a reset vector immediately after start, and you will have to type `c` (`continue`) to let execution continue.

**Comment by shp4rk** [comment]
Sorry for the confusion. I was on the wrong branch. Thanks for your reply!
