### ISSUE TITLE
Missed the dependency in BUILDING.md (mtools)

### ISSUE THREAD

**Issue by r3bb1t** [tandasat/Hypervisor-101-in-Rust#4]
Newly installed Ubuntu from microsoft store doesnt have the mcopy command availible by default, so running the [example](https://github.com/tandasat/Hypervisor-101-in-Rust/blob/main/BUILDING.md#testing-with-bochs) from documentation is not possible, to fix this, i suggest adding this to BUILDING.md:

> sudo apt install mtools

**Comment by r3bb1t** [comment]
also missed the **mkisofs**

> sudo apt install genisoimage

**Comment by tandasat** [comment]
Thanks for reporting this. Fixed with 3b9866ee1fbed02f5f976620a55b90b4b0da44d1.

The instructions for mtool already exists.
