### ISSUE TITLE
windows10 host build Hypervisor-101-in-Rust setup

### ISSUE THREAD

**Issue by cctv130** [tandasat/Hypervisor-101-in-Rust#8]
1、add **proc-macro2 = "1.0.66"** content in the project root directory *.toml

2、add **use proc_macro2 as _;** content to xtest/main.rs 

3、compile is successful

![1690101861244](https://github.com/tandasat/Hypervisor-101-in-Rust/assets/133784576/7d5ec74f-049a-474a-bbf6-ba3ec6ec6520)

**Comment by tandasat** [comment]
Thanks for reporting the issue. Resolved with b3f60f37257db8e77112b4ffbb436458f022cae6 by updating the dependencies.

**Comment by cctv130** [comment]
> Thanks for reporting the issue. Resolved with [b3f60f3](https://github.com/tandasat/Hypervisor-101-in-Rust/commit/b3f60f37257db8e77112b4ffbb436458f022cae6) by updating the dependencies.

This is what I should do, do you have any good ways to improve the compilation speed in rust? There seems to be little information in this area

**Comment by tandasat** [comment]
I am not sure as I have not felt the need of optimization. This project clean builds for debug in about 11 seconds on my primary environment, which is fine to me.

**Comment by cctv130** [comment]
> I am not sure as I have not felt the need of optimization. This project clean builds for debug in about 11 seconds on my primary environment, which is fine to me.

Through my efforts, I found some tools that can reduce the compilation time, which is very helpful during the development of rust.
https://github.com/mozilla/sccache
https://www.msys2.org/
[build]
rustc-wrapper = "C:/Users/botao/.cargo/bin/sccache.exe"
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=C:/msys64/mingw64/bin/ld.lld.exe"]
